/**
 * Selects the value of a configuration parameter of a company.
 *
 * @param p_cmp_id The ID of the company.
 * @param p_cfg_id The ID of the configuration parameter.
 */
create procedure abc_auth_get_config_value( in p_cmp_id @aut_company.cmp_id%type@,
                                            in p_cfg_id @aut_config.cfg_id%type@ )
reads sql data
-- type: singleton0
begin
  select cfg_value
  from   AUT_CONFIG_VALUE
  where  cmp_id = p_cmp_id
  and    cfg_id = p_cfg_id
  ;
end
