/**
 * Selects the details of a role.
 *
 * @param p_cmp_id The ID of the company.
 * @param p_rol_id The ID of the role.
 */
create procedure abc_company_role_get_details( in p_cmp_id @aut_company.cmp_id%type@,
                                               in p_rol_id @aut_role.rol_id%type@ )
reads sql data
-- type: row1
begin
  select rol_id
  ,      rol_weight
  ,      rol_name
  from   AUT_ROLE
  where  cmp_id = p_cmp_id
  and    rol_id = p_rol_id
  ;
end
